from bottled_kraken._image_edit.canvas_setup.lifecycle_and_image import ImageEditCanvasLifecycleMixin
from bottled_kraken._image_edit.canvas_setup.geometry_transform_state import ImageEditCanvasGeometryTransformStateMixin
from bottled_kraken._image_edit.canvas_setup.crop_erase_selection_state import ImageEditCanvasCropEraseSelectionStateMixin
from bottled_kraken._image_edit.canvas_setup.coordinate_projection import ImageEditCanvasCoordinateProjectionMixin
from bottled_kraken._image_edit.canvas_setup.painting_and_hit_testing import ImageEditCanvasPaintingAndHitTestingMixin
class ImageEditCanvasSetupMixin(ImageEditCanvasLifecycleMixin, ImageEditCanvasGeometryTransformStateMixin, ImageEditCanvasCropEraseSelectionStateMixin, ImageEditCanvasCoordinateProjectionMixin, ImageEditCanvasPaintingAndHitTestingMixin):
    pass
__all__ = ['ImageEditCanvasSetupMixin', 'ImageEditCanvasLifecycleMixin', 'ImageEditCanvasGeometryTransformStateMixin', 'ImageEditCanvasCropEraseSelectionStateMixin', 'ImageEditCanvasCoordinateProjectionMixin', 'ImageEditCanvasPaintingAndHitTestingMixin']
