from bottled_kraken._image_edit.dialog_actions_group.history_and_gray_contrast import ImageEditDialogHistoryGrayContrastMixin
from bottled_kraken._image_edit.dialog_actions_group.selection_crop_erase import ImageEditDialogSelectionCropEraseMixin
from bottled_kraken._image_edit.dialog_actions_group.filters_rotation_transform import ImageEditDialogFiltersRotationTransformMixin
class ImageEditDialogActionsMixin(ImageEditDialogHistoryGrayContrastMixin, ImageEditDialogSelectionCropEraseMixin, ImageEditDialogFiltersRotationTransformMixin):
    pass
__all__ = ['ImageEditDialogActionsMixin', 'ImageEditDialogHistoryGrayContrastMixin', 'ImageEditDialogSelectionCropEraseMixin', 'ImageEditDialogFiltersRotationTransformMixin']
